### ISSUE TITLE
Fehlende sharedlibraries

### ISSUE THREAD

**Issue by orat** [MobMonRob/JRTDE#11]
library path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Exception in thread "main" java.lang.UnsatisfiedLinkError: /usr/java/packages/lib/libjrtde.so: libboost_thread.so.1.71.0: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2452)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2508)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2704)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2669)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:807)
	at java.base/java.lang.System.loadLibrary(System.java:1907)
	at de.dhbw.rahmlab.rtde.test.Test.main(Test.java:21)

libboost_thread.so.1.71.0 fehlt. Vermutlich auf dem lokalen Entwickler-Rechner aber nicht ins repository eingecheckt.

**Comment by orat** [comment]
fixed by build of the c++ code which should be wrapped on the same pc.
